
name: Nextflow test

on:
  push:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
    - run: df -h
    - name: "node-cleanup"
      run: |
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
    - run: df -h
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.11
        channels: conda-forge,bioconda,defaults 
        channel-priority: true
    - uses: nf-core/setup-nextflow@v1
    - name: Test Nextflow pipeline
      run: |
        set -x
        bash test/run-tests.sh gh
